# Importar librerias

In [1]:
from keras.models import Sequential
from keras.layers import Dense,LSTM
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Procesamiento de datos

In [5]:
time_series = np.array([i for i in range(1,16)])
print(time_series)
train_size=int(len(time_series)*0.6)
train,test=time_series[:train_size],time_series[train_size:]
print(train)
print(test)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15]


# Preparación de datos para LSTM

In [6]:
def create_dataset(dataset,seq_lenght):
    data_x,data_y=[],[]
    for i in range(len(dataset)-seq_lenght):
        data_x.append(dataset[i:i+seq_lenght])
        data_y.append(dataset[i+seq_lenght])
    return np.array(data_x),np.array(data_y)

seq_lenght=4
train_x,train_y=create_dataset(train,seq_lenght)
test_x,test_y=create_dataset(test,seq_lenght)
print(train_x)
print(train_y)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[5 6 7 8 9]


# Modelo

In [7]:
model=Sequential()
model.add(LSTM(16, activation='relu',input_shape=(seq_lenght,1)))
model.add(Dense(1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [8]:
model.compile(optimizer='adam',loss='mse')
model.fit(train_x,train_y,epochs=500,batch_size=1,verbose=2)

Epoch 1/500
5/5 - 2s - 301ms/step - loss: 46.9488
Epoch 2/500
5/5 - 0s - 9ms/step - loss: 45.1373
Epoch 3/500
5/5 - 0s - 12ms/step - loss: 43.3002
Epoch 4/500
5/5 - 0s - 12ms/step - loss: 41.5007
Epoch 5/500
5/5 - 0s - 6ms/step - loss: 39.9092
Epoch 6/500
5/5 - 0s - 6ms/step - loss: 38.3701
Epoch 7/500
5/5 - 0s - 8ms/step - loss: 36.9060
Epoch 8/500
5/5 - 0s - 7ms/step - loss: 35.2522
Epoch 9/500
5/5 - 0s - 12ms/step - loss: 33.5172
Epoch 10/500
5/5 - 0s - 7ms/step - loss: 31.8210
Epoch 11/500
5/5 - 0s - 12ms/step - loss: 30.3489
Epoch 12/500
5/5 - 0s - 6ms/step - loss: 28.2593
Epoch 13/500
5/5 - 0s - 7ms/step - loss: 26.4993
Epoch 14/500
5/5 - 0s - 8ms/step - loss: 24.2229
Epoch 15/500
5/5 - 0s - 11ms/step - loss: 22.1976
Epoch 16/500
5/5 - 0s - 11ms/step - loss: 19.7736
Epoch 17/500
5/5 - 0s - 11ms/step - loss: 17.6435
Epoch 18/500
5/5 - 0s - 6ms/step - loss: 15.4414
Epoch 19/500
5/5 - 0s - 6ms/step - loss: 12.7853
Epoch 20/500
5/5 - 0s - 7ms/step - loss: 10.3760
Epoch 21/500
5/5 - 0

# Evaluación del modelo

In [9]:
Evaluacion=model.evaluate(test_x,test_y)
print(Evaluacion)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 454ms/step - loss: 1.2980
1.2980341911315918


In [10]:
y_pred=model.predict(test_x)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step
[[12.968195]
 [13.762484]]


# Parte 2

# Procesamiento de datos

In [12]:
time_series = np.array([i for i in range(1,1600)])
print(time_series)
train_size=int(len(time_series)*0.8)
train,test=time_series[:train_size],time_series[train_size:]
print(train)
print(test)

[   1    2    3 ... 1597 1598 1599]
[   1    2    3 ... 1277 1278 1279]
[1280 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293
 1294 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307
 1308 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321
 1322 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335
 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349
 1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363
 1364 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377
 1378 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391
 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405
 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419
 1420 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433
 1434 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447
 1448 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460 1461
 1462

# Preparación de datos para LSTM

In [13]:
def create_dataset(dataset,seq_lenght):
    data_x,data_y=[],[]
    for i in range(len(dataset)-seq_lenght):
        data_x.append(dataset[i:i+seq_lenght])
        data_y.append(dataset[i+seq_lenght])
    return np.array(data_x),np.array(data_y)

seq_lenght=4
train_x,train_y=create_dataset(train,seq_lenght)
test_x,test_y=create_dataset(test,seq_lenght)
print(train_x)
print(train_y)

[[   1    2    3    4]
 [   2    3    4    5]
 [   3    4    5    6]
 ...
 [1273 1274 1275 1276]
 [1274 1275 1276 1277]
 [1275 1276 1277 1278]]
[   5    6    7 ... 1277 1278 1279]


# Modelo

In [14]:
model=Sequential()
model.add(LSTM(16, activation='relu',input_shape=(seq_lenght,1)))
model.add(Dense(1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [15]:
model.compile(optimizer='adam',loss='mse')
model.fit(train_x,train_y,epochs=500,batch_size=1,verbose=2)

Epoch 1/500
1275/1275 - 3s - 3ms/step - loss: 83571.3281
Epoch 2/500
1275/1275 - 2s - 2ms/step - loss: 1.2339
Epoch 3/500
1275/1275 - 3s - 2ms/step - loss: 0.8041
Epoch 4/500
1275/1275 - 2s - 2ms/step - loss: 0.9071
Epoch 5/500
1275/1275 - 3s - 2ms/step - loss: 1.9945
Epoch 6/500
1275/1275 - 3s - 2ms/step - loss: 20.4920
Epoch 7/500
1275/1275 - 3s - 2ms/step - loss: 0.4836
Epoch 8/500
1275/1275 - 3s - 2ms/step - loss: 10.2268
Epoch 9/500
1275/1275 - 2s - 2ms/step - loss: 0.6171
Epoch 10/500
1275/1275 - 3s - 2ms/step - loss: 20.1338
Epoch 11/500
1275/1275 - 2s - 2ms/step - loss: 0.3853
Epoch 12/500
1275/1275 - 2s - 2ms/step - loss: 4.4239
Epoch 13/500
1275/1275 - 4s - 3ms/step - loss: 1.5757
Epoch 14/500
1275/1275 - 4s - 3ms/step - loss: 9.5717
Epoch 15/500
1275/1275 - 3s - 2ms/step - loss: 0.1211
Epoch 16/500
1275/1275 - 2s - 2ms/step - loss: 9.1368
Epoch 17/500
1275/1275 - 3s - 2ms/step - loss: 10.7571
Epoch 18/500
1275/1275 - 3s - 2ms/step - loss: 0.0277
Epoch 19/500
1275/1275 - 4s -

# Evaluación del modelo

In [16]:
Evaluacion=model.evaluate(test_x,test_y)
print(Evaluacion)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0228  
0.025268886238336563


In [17]:
y_pred=model.predict(test_x)
print(y_pred)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[1283.8612]
 [1284.8612]
 [1285.8611]
 [1286.8608]
 [1287.8608]
 [1288.8606]
 [1289.8605]
 [1290.8604]
 [1291.8602]
 [1292.8601]
 [1293.86  ]
 [1294.86  ]
 [1295.8597]
 [1296.8596]
 [1297.8595]
 [1298.8594]
 [1299.8593]
 [1300.8591]
 [1301.8591]
 [1302.8588]
 [1303.8588]
 [1304.8586]
 [1305.8585]
 [1306.8584]
 [1307.8583]
 [1308.8582]
 [1309.858 ]
 [1310.8579]
 [1311.8578]
 [1312.8575]
 [1313.8574]
 [1314.8573]
 [1315.8572]
 [1316.8572]
 [1317.8569]
 [1318.8568]
 [1319.8567]
 [1320.8566]
 [1321.8564]
 [1322.8564]
 [1323.8563]
 [1324.8561]
 [1325.856 ]
 [1326.856 ]
 [1327.8558]
 [1328.8556]
 [1329.8555]
 [1330.8553]
 [1331.8553]
 [1332.8551]
 [1333.855 ]
 [1334.855 ]
 [1335.8547]
 [1336.8546]
 [1337.8546]
 [1338.8545]
 [1339.8542]
 [1340.854 ]
 [1341.8539]
 [1342.8539]
 [1343.8536]
 [1344.8536]
 [1345.8535]
 [1346.8533]
 [1347.8531]
 [1348.853 ]
 [1349.853 ]
 [1350.8528]
 [1351.8527]
 [1352.8527]
 [1353.8524]
 [1354.8523]
 [1355.8523]
 [1356.8522