# Convolución 1 D

In [1]:
import numpy as np
x= np.array([2,1,0,1,2])
h= np.array([1,-1])
y= np.convolve(x,h,mode='valid')
print('Señal de salida después de la convolución:')
print(y)

Señal de salida después de la convolución:
[-1 -1  1  1]


# Convolución 2D

In [4]:
from scipy.signal import convolve2d

input_matrix=np.array([[1,2,3,3]
                       ,[4,5,6,6]
                       ,[7,8,9,9]
                       ,[7,8,9,9]])
kernel_matrix=np.array([[0,1,0],
                       [-1,1,-1],
                       [0,1,0]])
output_matrix=convolve2d(input_matrix,kernel_matrix,mode='valid')
print('Señal de salida después de la convolución:')
print(output_matrix)

Señal de salida después de la convolución:
[[5 7]
 [5 7]]


In [5]:
output_matrix=convolve2d(input_matrix,kernel_matrix,mode='same')
print('Señal de salida después de la convolución:')
print(output_matrix)

Señal de salida después de la convolución:
[[ 3  3  4  6]
 [ 7  5  7 12]
 [10  5  7 15]
 [ 6  0  1  9]]
