# Ejemplo de Tokenización con keras

In [4]:
import keras
import tensorflow as tf

In [2]:
frases=[
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo'
]

In [5]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index=tokenizer.word_index
print('word_index = ',word_index)

word_index =  {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


In [6]:
secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)
#

secuencias =  [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


In [7]:
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)

relleno =
  [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


# Ejemplo de Tokenización con keras 2

In [8]:
frases=[
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen día, como estás'
]

In [9]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index=tokenizer.word_index
print('word_index = ',word_index)

word_index =  {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'buen': 7, 'día': 8, 'como': 9, 'estás': 10}


In [10]:
secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)
#

secuencias =  [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]


In [11]:
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)

relleno =
  [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


# Ejemplo de Tokenización con keras 3

In [12]:
frases=[
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen día, como estás hoy'
]

In [13]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index=tokenizer.word_index
print('word_index = ',word_index)
#

word_index =  {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'día': 9, 'como': 10, 'estás': 11, 'hoy': 12}


In [15]:
secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)
#

secuencias =  [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]


In [16]:
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)

relleno =
  [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


# Ejemplo de Tokenización con keras 4

In [17]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index=tokenizer.word_index
print('word_index = ',word_index)
#

word_index =  {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'día': 9, 'como': 10, 'estás': 11, 'hoy': 12}


In [18]:
secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)
#

secuencias =  [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]


In [19]:
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias,
                                                        padding='post',
                                                        truncating='post')
print('relleno =\n ',relleno)

relleno =
  [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
